your_blogs/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()], render_kw={"rows":10})
    submit= SubmitField('Post')

your_blogs/main/routes.py
from flask import render_template, request, Blueprint
from your_blogs.models import Post

main = Blueprint('main', __name__)

@main.route("/")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_created.desc()).paginate(per_page=5, page = page)
    return render_template('home_page.html', posts=posts)

@main.route('/about')
def about():
    return render_template('about.html', title='About')

your_blogs/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from your_blogs import db
from your_blogs.models import  Post
from your_blogs.posts.forms import PostForm
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, body = form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Post has been created", 'success')
        return redirect(url_for('main.home'))
    return render_template('new_post.html', title='New Post', form=form, legend='New post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id);   
    return render_template('post.html', title=post.title, post=post)  

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author !=current_user:
        abort(403); 
    form = PostForm(); 
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.content.data
        db.session.commit(); 
        flash("Your post has been updated", "success")
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.body
    return render_template('new_post.html', title='Update Post',form=form, legend='Update post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post); 
    db.session.commit()
    flash("Your post has been deleted", "success"); 
    return redirect(url_for('main.home'))

your_blogs/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from your_blogs import bcrypt, db
from your_blogs.models import User, Post
from your_blogs.users.forms import RegisterForm, LoginForm, UpdateForm, RequestResetForm, ResetPasswordForm
from flask_login import login_user, current_user, logout_user, login_required
from your_blogs.users.utils import save_avatar, send_reset_email

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username = form.username.data, password_hash= hashed_password, email = form.email.data)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}", 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if user and bcrypt.check_password_hash(user.password_hash, form.password.data):
            login_user(user, remember=form.remember.data)
            flash("Login Successful", 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsucessful. Please check your username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    avatar = url_for('static', filename=current_user.avatar)
    form = UpdateForm()
    if form.validate_on_submit():
        if form.avatar.data:
            avatar_name = save_avatar(form.avatar.data)
            current_user.avatar = avatar_name
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Account update sucessful", "success ")
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data  = current_user.email
    return render_template('account.html', title= 'Account', avatar=avatar, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404(); 
    posts = Post.query.filter_by(author=user)\
    .order_by(Post.date_created.desc())\
    .paginate(per_page=5, page = page)
    return render_template('user_post.html', posts=posts, username=username)

@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user  = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset password", "info")
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None: 
        flash("Token invalid or expired", "warning")
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password_hash = hashed_password
        db.session.commit()
        flash(f"Password Updated! You are now able to login", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

your_blogs/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About Page</h1>
<div class="content-section">
    <p>Your Blogs is a blog website for people to write and share their stories.</p>
    <p>Made by Sunny Wahane</p>
</div>

{% endblock %}

your_blogs/templates/account.html
{% extends 'base.html' %}
{% block content %}
    <div class="user-info">
        <img src="{{ avatar }}" alt="" class="rounded-circle account-img">
        <div>
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <div class="update-form">
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group mb-4">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                     {{ form.username(class="form-control form-control-lg w-50 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.username(class="form-control form-control-lg w-50") }}
                {% endif %}

            </div>
             <div class="form-group mb-4">
                {{ form.email.label(class="form-control-label") }}
                 {% if form.email.errors %}
                     {{ form.email(class="form-control form-control-lg w-50 is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.email(class="form-control form-control-lg w-50") }}
                {% endif %}
            </div>
            <div class="form-group mb-4">
                {{ form.avatar(class="form-control-file") }}
                {% if form.avatar.errors %}
                    {% for error in form.avatar.errors %}
                    <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                <br>
                {{ form.avatar.label() }}
            </div>
        </fieldset>
        <div class="form-group mb-3">
            {{ form.submit(class="btn btn-lg btn-outline-dark") }}
        </div>
    </form>
</div>

{% endblock %}

your_blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
    <title>Blog - {{ title }}</title>
    {% else %}
    <title>Blog</title>
    {% endif %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">
    <h2 class="navbar-brand">Your Blogs</h2>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
     <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.home') }}">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
      </li>
    </ul>
    <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
        </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            </li>
            
        {% else %}
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
            </li>
        {% endif %}
    </ul>
         </div>
     </div>
</nav>
    <div class="container mid-section">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="flash-message alert alert-{{ category }} mb-3">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
         {% block content %}
         {% endblock %}
    </div>
<footer>
    {% block footer %}
    {% endblock %}
</footer>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>

your_blogs/templates/home_page.html
{% extends 'base.html' %}
{% block content %}
    {% for post in posts.items %}
    <div class="post-data">
        <div class="post-header">
            <img class="rounded-circle account-img" src="{{ url_for('static', filename = post.author.avatar) }}" alt="">
            <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p>By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_created.strftime('%Y-%m-%d') }}</p>
        </div>
        <div class="post-body">
            <p>{{ post.body[0:400] }} ...</p>
        </div>
    </div>
    {% endfor %}
   
{% endblock %}

{% block footer %}
 {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
 {% if page_num %}
 {% if page_num == posts.page %}
 <a class="btn btn-dark mb-4" href="{{ url_for('main.home', page=page_num) }}">{{page_num}}</a>
 {% else %}
 <a class="btn btn-outline-dark mb-4" href="{{ url_for('main.home', page=page_num) }}">{{page_num}}</a>
 {% endif %}
 {% else %}
 ...
 {% endif %}
 {% endfor %}
{% endblock %}

your_blogs/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 mt-4 w-50">Welcome to Your Blogs</legend>
             <div class="form-group mb-4">
                {{ form.username.label }}
                {% if form.username.errors %}
                     {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
             </div>
             <div class="form-group mb-4">
                {{ form.password.label }}
                 {% if form.password.errors %}
                     {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check mb-3">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
         <div class="form-group mb-3">
            {{ form.submit(class="btn btn-lg btn-outline-dark") }}
        </div>
        <small class="text-muted ml-2">
            <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
        </small>
        <div class="border-top pt-2 w-50">
            <small class="text-muted">
                New to Your Blogs ? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
            </small>
        </div>
    </form>
</div>
{% endblock %}

your_blogs/templates/new_post.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 mt-4">{{ legend }}</legend>
             <div class="form-group mb-4">
                {{ form.title.label }}
                {% if form.title.errors %}
                     {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
                </div>
                <div class="form-group mb-4">
                    {{ form.content.label }}
                    {% if form.content.errors %}
                         {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                          {{ form.content(class="form-control form-control-lg ") }}
                    {% endif %}
                    </div>
        </fieldset>
         <div class="form-group mb-3">
            {{ form.submit(class="btn btn-lg btn-outline-dark") }}
        </div>
    </form>
</div>
{% endblock %}

your_blogs/templates/post.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div>
          <img class="rounded-circle account-img" src="{{ url_for('static', filename = post.author.avatar) }}" alt="">
            <h2>{{ post.title }}</h2>
            <p>By {{ post.author.username }} on {{ post.date_created.strftime('%Y-%m-%d') }}</p>
            {% if post.author == current_user %}
            <div>
                <a href="{{ url_for('posts.update_post',post_id=post.id) }} " class="btn btn-secondary btn-sm m-1">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1"  data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>
            </div>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input type="submit" class="btn btn-danger" value="Confirm">
          </form>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
  <div class="content-section">
    <pre>{{ post.body }}</p>
  </div>
           
    </div>
    </div>
{% endblock %}

your_blogs/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4 mt-4">Welcome to Your Blogs</legend>
            <div class="form-group mb-4">
                {{ form.username.label }}
                {% if form.username.errors %}
                     {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.username(class="form-control form-control-lg") }}
                {% endif %}

            </div>
             <div class="form-group mb-4">
                {{ form.email.label }}
                 {% if form.email.errors %}
                     {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.email(class="form-control form-control-lg ") }}
                {% endif %}
            </div>
            <div class="form-group mb-4">
                {{ form.password.label }}
                 {% if form.password.errors %}
                     {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group mb-4">
                {{ form.confirm_password.label }}
                 {% if form.confirm_password.errors %}
                     {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                      {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group mb-3">
            {{ form.submit(class="btn btn-lg btn-outline-dark") }}
        </div>
        <div class="border-top pt-2">
            <small class="text-muted">
                Already have a Account ? <a class="ml-2" href="{{ url_for('users.login') }}">Login</a>
            </small>
        </div>
    </form>
</div>
{% endblock %}

your_blogs/templates/reset_request.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <div class="form-group mb-4">
            {{ form.email.label }}
             {% if form.email.errors %}
                 {{ form.email(class="form-control form-control-lg w-50 is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                  {{ form.email(class="form-control form-control-lg w-50") }}
            {% endif %}
        </div>
    </fieldset>
     <div class="form-group mb-3">
        {{ form.submit(class="btn btn-lg btn-outline-dark") }}
    </div>
</form>
{% endblock %}

your_blogs/templates/reset_token.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <div class="form-group mb-4">
            {{ form.password.label }}
             {% if form.password.errors %}
                 {{ form.password(class="form-control form-control-lg w-50 is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                  {{ form.password(class="form-control form-control-lg w-50") }}
            {% endif %}
        </div>
        <div class="form-group mb-4">
            {{ form.confirm_password.label }}
             {% if form.confirm_password.errors %}
                 {{ form.confirm_password(class="form-control form-control-lg w-50 is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                  {{ form.confirm_password(class="form-control form-control-lg w-50") }}
            {% endif %}
        </div>
    </fieldset>
     <div class="form-group mb-3">
        {{ form.submit(class="btn btn-lg btn-outline-dark") }}
    </div>
</form>
{% endblock %}

your_blogs/templates/user_post.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mb-3">Posts by {{ username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <div class="post-data">
        <div class="post-header">
            <img class="rounded-circle account-img" src="{{ url_for('static', filename = post.author.avatar) }}" alt="">
            <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p>By <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_created.strftime('%Y-%m-%d') }}</p>
        </div>
        <div class="post-body">
            <p>{{ post.body[0:400] }} + ...</p>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

    {% block footer %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if page_num == posts.page %}
    <a class="btn btn-dark mb-4" href="{{ url_for('users.user_posts',username=username, page=page_num) }}">{{page_num}}</a>
    {% else %}
    <a class="btn btn-outline-dark mb-4" href="{{ url_for('users.user_posts',username=username, page=page_num) }}">{{page_num}}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
{% endblock %}